title: Jesse Trippe, Product and UX Designer

include: ['_pages']

exclude: [presentation, sprout-social]

plugins:
- jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 2 versions

collections:
  work_items:
    output: true

sass:
  style: compressed
